### ISSUE TITLE
Undefined Offset 1 on post api

### ISSUE THREAD

**Issue by adnan5253** [facebookarchive/php-graph-sdk#1082] opened 2018-11-12 18:42 UTC
Hi!
I use the following code to publish posts to facebook pages. 
`$fb->post('/'.$pageId.'/photos',$data,$accessToken)`.

This code worked just fine until now, but from couple of days it has started giving an exception saying "Undefined Offset 1".

 However the post still gets published to the page but throws this exception immediately. I am currently using facebook sdk v5.6, facebook graph v3.2, PHP v7.0.

**Comment by yguedidi** [comment] 2018-11-12 22:25
@adnan5253 isn't this a duplicate of #1076? If so, please close this

**Comment by adnan5253** [comment] 2018-11-13 08:50
I went through the #1081 and was able to fix my post API, but the fix doesn't seem to work for my GET API.

i.e `$fb->get('/'.$pageId.'/posts,$accessToken)`

This API still throws an exception of "Undefined offset 1".

**Closed as completed** 2019-02-12 13:06 UTC
