### ISSUE TITLE
Can't Load URL: The domain of this URL isn't included in the app's domains. To be able to load this URL, add all domains and subdomains of your app to the App Domains field in your app settings.

### ISSUE THREAD

**Issue by iamkarthick** [facebookarchive/php-graph-sdk#1050] opened 2018-08-30 07:04 UTC
We've had implement and working the social login 2 days back. But today have the issues
 
"Can't Load URL: The domain of this URL isn't included in the app's domains. To be able to load this URL, add all domains and subdomains of your app to the App Domains field in your app settings."

We've checked the app settings for Login, and all of our callback URLs are still there and correct.

These errors started today (2018-08-29 20:00 UTC).

Solutions:

After along research, the problem got fixed. 

Please use the PHP SDK 5.6.2. And edit the following files in the FacebookRedirectLoginHelper.

Edit in PHP SDK
Find file: facebook\graph-sdk\src\Facebook\Helpers\FacebookRedirectLoginHelper.php

Find word
$redirectUrl = FacebookUrlManipulator::removeParamsFromUrl($redirectUrl, ['state','code']);
Change to
$redirectUrl = FacebookUrlManipulator::removeParamsFromUrl($redirectUrl, ['state','code','enforce_https']);

**Comment by gianpaolodn** [comment] 2018-08-30 07:50
duplicate:  #1049

**Comment by LifullPrasetyama** [comment] 2018-08-30 10:18
good job, saved my life

**Comment by vanloc0301** [comment] 2018-09-17 12:37
Thanks man.

**Comment by mihirverma** [comment] 2018-09-18 09:34
i still have error please give me the solution

Graph returned an error: Can't load URL: The domain of this URL isn't included in the app's domains. To be able to load this URL, add all domains and sub-domains of your app to the App Domains field in your app settings.

**Comment by yguedidi** [comment] 2018-09-29 07:55
closing as duplicate of #1049

**Closed as completed by yguedidi** 2018-09-29 07:55 UTC
