### ISSUE TITLE
Facebook Login : Error validating verification code

### ISSUE THREAD

**Issue by nikolasr200** [facebookarchive/php-graph-sdk#1051] opened 2018-08-30 11:20 UTC
as described here https://stackoverflow.com/questions/52095150/facebook-login-error-validating-verification-code

As of today an application that i have keeps getting the following error while using Facebook Login Api.

>Error validating verification code. Please make sure your redirect_uri is identical to the one you used in the OAuth dialog
> request

Last successfull attempt was yesterday night 2018-08-29 23:40:00 and since then all loging attempts end up to redirect_url mismatch.

My call back url is like

> https://mysubdomain.mysite.gr/index.php?r=site/callbackfb

also tried alternative

> https://mysubdomain.mysite.gr/index.php/site/callbackfb

but still no success.
No change was made to the application and nothing seems to justify the exception. Tried also with latest sdk librady, but i still get the same error.

Any help would be much appreciated.

**Comment by gianpaolodn** [comment] 2018-08-30 12:31
duplicate #1049

**Comment by nikolasr200** [comment] 2018-08-30 14:04
I ended up with a different solution thanks to https://github.com/facebook/php-graph-sdk/issues/1049 we added the parameter to the verify url until library is fixed.

**Comment by yguedidi** [comment] 2018-09-29 08:12
closing as duplicate of #1049

**Closed as completed by yguedidi** 2018-09-29 08:12 UTC

**Comment by hatvanibence** [comment] 2020-05-09 13:02
Hello!
I did everything correctly, but I still have this issue. Error validating verification code. Please make sure your redirect_uri is identical to the one you used in the OAuth dialog request

What is the problem? :/
